[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.check-manifest]
ignore = [
  ".aicoe-ci.yaml",
  ".pre-commit-config.yaml",
  ".prow.yaml",
  ".thoth.yaml",
  "CHANGELOG.md",
  "code/*",
  "tests/*",
  "thoth-glyph"
]
